export const URL = {
  BASE_URL: "http://localhost:5000",
  CLIENT_URL: "http://localhost:3000",
};

export const GLOBALTYPES = {
  ALERT: "ALERT",
  SELECTED_FILM: "SELECTED_FILM",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  SUBMIT_NEW_LIST: "SUBMIT_NEW_LIST",
  GET_ALL_FILM: "GET_ALL_FILM",
  GET_FILM_BY_ID: "GET_FILM_BY_ID",
  GET_ALL_USER: "GET_ALL_USER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
};
